### ISSUE TITLE
Add support for extra field

### ISSUE THREAD

**Issue by inorick** [zip-rs/zip#186]
Support for the [extra field](https://en.wikipedia.org/wiki/Zip_(file_format)#Extra_field) of ZIP file headers is currently marked as [future work](https://github.com/mvdnes/zip-rs/blob/8a6ca63728e4fe15e57e88efcc6c865d5e23680a/src/write.rs#L601).

My idea for an implementation is to add `*_with_extra_data` versions of the `start_file` and `start_file_from_path` methods that accept a slice with extra data to fill the extra field. The data would then be part of the `ZipFileData` struct.

I started preliminary work on it here: https://github.com/inorick/zip-rs/pull/1/commits/4393671828d2ab6ff95150d17f5109b2c05cc237

Please let me know what you think of this approach.

**Comment by Plecra** [comment]
Thanks for starting on the design! This seems reasonable with the crate's current API, and I'd be happy to merge a simple implementation so long as it had a solid set of tests.

I'd only add that the user should be able to pass owned data to to `*_with_extra_data` as they do for the `name`. It's likely the buffers they create will be unique to each file.

**Comment by Plecra** [comment]
I'd like to welcome anyone looking at this issue to make a PR implementing the `extra_field` API for 0.5. Though it would be very useful, I'm not planning on adding more features to this version of the API myself

**Comment by n3vu0r** [comment]
I'm interested in aligned files which seems to be usually achieved by appending zeros to the local header as part of the extra field. Instead of passing the extra data directly, I would suggest to wrap it in a closure which itself provides a preliminary `data_start()`: 

```rust
pub fn start_file_with_extra_data<S, E>(&mut self, name: S, mut options: FileOptions, extra_data: E) -> ZipResult<()>
        where
            S: Into<String>,
            E: FnOnce(u64) -> AsRef<[u8]>,
```
This would allow to calculate the pad length which I think is not reliable otherwise:
```rust
zip.start_file_with_extra_data("file.ext", fopts, |data_start| vec![0; (align - data_start % align) % align]);
```
And it doesn't bloat the original use case:
```rust
zip.start_file_with_extra_data("file.ext", fopts, |_| extra_data);
```
What do you think? If nobody is working on a PR, I could give it a try soon.

**Comment by n3vu0r** [comment]
Alternative design:

Let `start_file()` return the preliminary `data_start()` instead of `()` (not sure if this is a breaking change, otherwise add a separate `data_start()` method for `ZipWriter` as well). And then the extra data or normal file data is simply written via `io::Write` and optionally at some point the data which has already been written can be marked as extra data by calling `end_extra_data()` which would just update the extra data length in the local file header.

**Comment by inorick** [comment]
I created an updated PR (#208) with the suggested changes (and clippy fixes). Please let me know what you think.

I just now realized that in the meantime a second PR with a separate implementation was created but I did not have a look at it yet.

**Comment by Plecra** [comment]
Done! Thanks for PR #200
