### ISSUE TITLE
Repository link is wrong

### ISSUE THREAD

**Issue by fungos** [zip-rs/zip#225]
```
repository = "https://github.com/zip/zip-rs.git"
``` 
https://github.com/zip-rs/zip/blob/master/Cargo.toml#L6

causing `crates.io` to redirect to a github 404 page.

**Comment by striezel** [comment]
Correct, and there already is a pull request to change that: https://github.com/zip-rs/zip/pull/224

**Comment by Ch4s3r** [comment]
Just came here to report this, but there was already one ahead of me :)

**Comment by striezel** [comment]
This issue is already fixed in PR #224, and that PR has been merged, too. However, for the change to take effect and be visible on crates.io, the owner(s) of the crate have to publish a new version on crates.io.

@Plecra or @mvdnes or whoever usually does this: Could you please publish the current version of the master branch publish as a new version of the [zip crate on crates.io](https://crates.io/crates/zip)? Thanks.

**Comment by Plecra** [comment]
Thanks for bugging me on this. I'll try to be less hesitant with releases 😄
