### ISSUE TITLE
Can we expose `CentralDirectoryEnd::find_and_parse`?

### ISSUE THREAD

**Issue by jooyunghan** [zip-rs/zip#248]
I found that inspecting a zip file can benefit from `CentralDirectoryEnd::find_and_parse` since everything starts from there. Can we expose the API as public?

**Comment by Plecra** [comment]
Sure can! I want to put this in a subcrate which will expose the zip algorithms with a less stable API. Refactoring the current implementation into an in-tree dependency would be perfect

**Comment by jooyunghan** [comment]
Sounds great! Thank you.

**Comment by zamazan4ik** [comment]
@Plecra do you have any updates on this?

**Comment by Plecra** [comment]
Moving the internal parsing apis into a subcrate (`zip-format`?) would be a perfectly solid solution. It should be unstable, as in pre-1.0, and should make it cleaar that version bumps are common because `zip` is the stable API. Maybe at some point it could be stabilized once the core crate itself is more secure.

**Comment by Plecra** [comment]
This is WIP in #292 and kinda subsumed by #58. Lets call this "closing as duplicate" :D
