### ISSUE TITLE
bzip2 allows attackers to cause a denial of service via a large file that triggers an integer overflow

### ISSUE THREAD

**Issue by Magicloud** [zip-rs/zip#357]
The bzip2 crate before 0.4.4 for Rust allow attackers to cause a denial of service via a large file that triggers an integer overflow in mem.rs. NOTE: this is unrelated to the https://crates.io/crates/bzip2-rs product.

**Comment by mcandre** [comment]
^ This.

Please introduce `cargo audit` into the CI/CD pipeline, in order to catch vulnerabilities sooner.

https://crates.io/crates/cargo-audit

`cargo audit` should run at least during the pull request review process, so that proposed code changes will be scanned and reported.

And `cargo audit` should run at least at every midnight UTC, so that latent vulnerabilities will be scanned and reported.

Unfortunately, I am not sure that dependabot knows to run `cargo audit` yet.

**Comment by Plecra** [comment]
see #335 for the history of this issue. respond there if you'd like to reevaluate :)
